version: '3.8'

services:
  issuance-service:
    build:
      context: ./backend/issuance
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - WORKER_ID=issuance-worker-1
    volumes:
      - issuance-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  verification-service:
    build:
      context: ./backend/verification
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - WORKER_ID=verification-worker-1
      - ISSUANCE_SERVICE_URL=http://issuance-service:3001
    volumes:
      - verification-data:/app/data
    depends_on:
      - issuance-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_ISSUANCE_API_URL=http://localhost:3001/api
      - REACT_APP_VERIFICATION_API_URL=http://localhost:3002/api
    depends_on:
      - issuance-service
      - verification-service
    restart: unless-stopped

volumes:
  issuance-data:
  verification-data: